import aiquiz from "../assets/quiz.svg";
import smartwatch from "../assets/smartwatch.svg";

const projects = [
  {
    name: "AI Quiz Generator",
    icon: aiquiz,
    technologies: [
      "Node.js ",
      "Express.js",
      "MongoDB",
      "OpenAI API",
      " React.js ",
      "Vite",
      "TailwindCSS",
    ],
    link: "https://github.com/Khushijain83037/ai-quiz",
    description:
      "AI Quiz is a fullstack web application where users can register, log in, and attempt quizzes generated by AI. User performance is stored and displayed in the dashboard. It integrates OpenAI for dynamic question generation.",
  },
  {
    name: "Smartwatch E-Commerce Platform",
    icon: smartwatch,
    technologies: ["Mern Stack"],
    link: "https://github.com/Khushijain83037/Smartwatch",
    description:
      "A full-featured and responsive e-commerce platform for smartwatches, built using the MERN stack: MongoDB, Express.js, React.js, and Node.js.",
  },
];

export default projects;
